version: 0.1.0

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - epub
  - pdf

python:
  install:
    - requirements: docs/requirements.txt