LAYER_RESULT_COUNT_MAP = {
    'States': 57,
    'Counties': 150,
    'Census Tracts': 1000
}

FEATURE_ATTRIBUTE_MAP = {
    'ZCTA5': 'zip code tabulation area',
    'TTRACT': 'tribal census tract',
    'TRACT': 'tract',
    'TBLKGRP': 'tribal block group',
    'BLKGRP': 'block group',
    'BLOCK': 'block',
    'SDUDI': 'school district (unified)',
    'SDSEC': 'school district (secondary)',
    'SDELM': 'school district (elementary)',
    'COUSUB': 'county subdivision',
    'CONCITY': 'consolidated city',
    'PLACE': 'place',
    'ANRC': 'alaskan national regional corporation',
    'CD116': 'congressional district',
    'SLDU': 'state legislative district (upper)',
    'SLDL': 'state legislative district (lower)',
    'REGION': 'region',
    'DIVISION': 'division',
    'CNECTA': 'combined new england city and town area',
    'NECTA': 'new england city and town area',
    'CSA': 'combined statistical area',
    'CBSA': 'metropolitan statistical area/micropolitan statistical area',
    'METDIV': 'metropolitan division',
    'STATE': 'state',
    'COUNTY': 'county'
}

# dont know what to do with 28-48, 62-66, clarify CBSA, and then congressional districts

LAYER_NAME_MAP = {
    'Census Regions': 'region',
    'States': 'state',
    'Counties': 'county'
}

FIPS_TO_ABBR = {
   "01":"AL",
   "02":"AK",
   "04":"AZ",
   "05":"AR",
   "06":"CA",
   "08":"CO",
   "09":"CT",
   "10":"DE",
   "11":"DC",
   "12":"FL",
   "13":"GA",
   "15":"HI",
   "16":"ID",
   "17":"IL",
   "18":"IN",
   "19":"IA",
   "20":"KS",
   "21":"KY",
   "22":"LA",
   "23":"ME",
   "24":"MD",
   "25":"MA",
   "26":"MI",
   "27":"MN",
   "28":"MS",
   "29":"MO",
   "30":"MT",
   "31":"NE",
   "32":"NV",
   "33":"NH",
   "34":"NJ",
   "35":"NM",
   "36":"NY",
   "37":"NC",
   "38":"ND",
   "39":"OH",
   "40":"OK",
   "41":"OR",
   "42":"PA",
   "44":"RI",
   "45":"SC",
   "46":"SD",
   "47":"TN",
   "48":"TX",
   "49":"UT",
   "50":"VT",
   "51":"VA",
   "53":"WA",
   "54":"WV",
   "55":"WI",
   "56":"WY",
   "60":"AS",
   "66":"GU",
   "69":"MP",
   "72":"PR",
   "78":"VI",
}

ABBR_TO_FULL = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming',
    'AS': 'American Samoa',
    'GU': 'Guam',
    'MP': 'Commonwealth of the Northern Mariana Islands',
    'PR': 'Puerto Rico',
    'VI': 'Virgin Islands'
}

FIPS_TO_FULL = {k: ABBR_TO_FULL[v] for k, v in FIPS_TO_ABBR.items()}

ABBR_TO_FULL_REGEX = '(' +  '|'.join([f'(?P<{v}>(?<![A-Za-z0-9])({k}|{k.lower()})(?![A-Za-z0-9]))' for k, v in {k: v.replace(' ', '_') for k, v in ABBR_TO_FULL.items()}.items()]) + ')'